# Pull official base image
FROM python:3.12.4-slim-bookworm

# Set working directory
WORKDIR /usr/src/app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update \
  && apt-get -y install gcc postgresql netcat-openbsd \
  && apt-get clean

# Copy the requirements.txt file created outside Docker
COPY ./app/requirements.txt .

# Install dependencies using pip
RUN pip install --no-cache-dir -r ./requirements.txt
COPY ./poetry.lock ./

# Copy entrypoint.sh to a persistent location
COPY ../development/entrypoint.sh ./
RUN chmod +x ./entrypoint.sh

# Copy the app directory
COPY ../app ./

# Expose port 8000
EXPOSE 8000

# Use entrypoint.sh to start the server
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
