repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1 # Use the latest stable version
    hooks:
      - id: black
        name: black
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287 # Use the latest stable version
    hooks:
      - id: ruff
        name: ruff
        args: [
            "--fix", # Enable automatic fixing, including import sorting
            "--select",
            "ALL", # Apply all linting rules by default
            "--exclude",
            "app/movies/migrations/*", # Exclude migrations directory
            "--exclude",
            "tasks.py", # Exclude tasks.py
          ]
        language_version: python3

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: bandit
        args: [
            "-iii", # Report all confidence levels
            "-ll", # Report all severity levels
          ]
        language_version: python3
