[tool.poetry]
name = "django-tdd-docker"
version = "0.1.0"
description = ""
authors = ["kvncampos <kvnelpdfw@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "5.0.7"
djangorestframework = "3.15.2"
docker = "^7.1.0"
compose = "^1.5.0"
invoke = "^2.2.0"
psycopg2-binary = "^2.9.9"
pytest = "^8.3.2"
pytest-django = "4.8.0"
ruff = "^0.6.1"
pre-commit = "^3.8.0"
bandit = "^1.7.9"
gunicorn = "^23.0.0"
dj-database-url = "^2.2.0"
python-dotenv = "^1.0.1"
whitenoise = "^6.7.0"
pytest-cov = "^5.0.0"
black = "^24.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = false
exclude = '''
/(
    \.git
  | \.venv
  | \.mypy_cache
  | \.pytest_cache
  | __pycache__
  | build
  | dist
  | migrations
  | movies/migrations  # Exclude migrations directory in movies app
)/
'''

[tool.ruff]
# Deprecated settings migrated to the lint section
line-length = 88

[tool.ruff.lint]
# Select all rules but apply exclusions
select = ["ALL"]

ignore = [
    "E501",  # Ignore line-length errors (handled by Black)
    "E231",  # Ignore missing whitespace around operators (handled by Black)
    "E203",  # Ignore whitespace before ':' (handled by Black)
    "D100",  # Ignore missing docstring in public module
    "D104",  # Ignore missing docstring in public package
    "ANN201" # Ignore missing return type annotation for public functions
]

exclude = [
    "*.pyc",                  # Exclude any .pyc files
    "__pycache__/",           # Exclude __pycache__ directories
    "tests/*",                # Exclude tests directory
    "movies/migrations/*",    # Exclude migrations in movies app
    "drf_project/settings.py" # Exclude drf_project settings
]
